language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn build # npm run build
deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  local_dir: .vuepress/dist
  github_token: $blog # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  keep_history: true
  on:
    branch: blog